version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Karachi
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(actions)"

  - package-ecosystem: pip
    directory: /platform
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Asia/Karachi
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: docker
    directory: /platform
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Asia/Karachi
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(container)"
